services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
  
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: workspace
    working_dir: /var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}          
    volumes:
      - .:/var/www/html
    networks:
      - laravel
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "9001:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: